name: Build and deploy shrinkLink api
run-name: ${{ github.actor }} running production build for deployment
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    ubuntu-job:
        environment:
            name: testing
        container: python:3.14-slim
        env:
            DB_HOSTNAME: postgres
            DB_PORT: 5432
            DB_PASSWORD: postgres
            DB_NAME: shrinklink_test
            DB_USERNAME: postgres
            DB_DRIVER: postgresql
            SECRET_KEY: 8c749cf7f2b124d6805378792e330a7889887a30242056db3977f99a3fb51db5
            ALGORITHM: HS256
            ACCESS_TOKEN_EXPIRE_MINUTES: 1440
            BACKEND_URL: http://localhost:8000

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        runs-on: ubuntu-latest
        steps:
            - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "on the branch ${{ github.ref }}, and repository ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v5
            - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            - name: install python version 3.14.0
              uses: actions/setup-python@v6
              with:
                python-version: '3.14.0'
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install dependencies from requirements.txt
              run: pip install -r requirements.txt
            - name: install pytest and run unit test
              run: |
                pip install pytest
                pytest
